### ISSUE TITLE
Cannot call xBinnedModulationCube.fit() and xBinnedModulationCube.plot() one after the other

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#140]
This is most likely due to something not being reset properly and should be trivial to fix. Here is the full stack trace for completeness.

```
Traceback (most recent call last):
  File "examples/gk_per.py", line 101, in <module>
    run(save_plots=True)
  File "examples/gk_per.py", line 97, in run
    analyze()
  File "examples/gk_per.py", line 90, in analyze
    _mcube.plot()
  File "/data/work/xpe/ximpol/ximpol/evt/binning.py", line 750, in plot
    self.plot_polarization_degree(show=False)
  File "/data/work/xpe/ximpol/ximpol/evt/binning.py", line 708, in plot_polarization_degree
    plt.errorbar(_x, _y, _dy, _dx, fmt='o', **kwargs)
  File "/data/install/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2830, in errorbar
    **kwargs)
  File "/data/install/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/data/install/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 2913, in errorbar
    yo, _ = xywhere(y, right, noxlims & everymask)
  File "/data/install/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 2861, in xywhere
    assert len(xs) == len(ys)
AssertionError

```

**Comment by ndilalla** [comment]
This error is due to the fit_results list that is not reset before call fit_bin in the mcube plot function. So, if the fit was already called before, the results in the list are duplicated.
To solve this issue I put:

```
if fit:
    self.fit_results = []
```

at the beginning of the plot function. Closing this one.
