### ISSUE TITLE
xModulationCube.quick_analysis() crash

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#58]
This is pretty bad.

If I do

```
xpobssim.py -c ximpol/srcmodel/config/test_single_point_source.py -d xxx
```

with a duration larger than ~2300 s, bin the data in MCUBE mode and run the quick analysis, it crashes with 

> > > /data/work/xipe/ximpol/ximpol/irf/mrf.py:230: RuntimeWarning: invalid value encountered in sqrt
> > >   popt, pcov = curve_fit(f, _x, _y, p0, numpy.sqrt(_y))
> > > Traceback (most recent call last):
> > >   File "ximpol/evt/binning.py", line 455, in <module>
> > >     c.quick_analysis()
> > >   File "ximpol/evt/binning.py", line 430, in quick_analysis
> > >     _res = self.fit_bin(i)
> > >   File "ximpol/evt/binning.py", line 395, in fit_bin
> > >     fit_results = xAzimuthalResponseGenerator.fit_histogram(hist)
> > >  File "/data/work/xipe/ximpol/ximpol/irf/mrf.py", line 246, in fit_histogram
> > >     chisquare = ((exp - obs)**2/exp).sum()
> > > ValueError: operands could not be broadcast together with shapes (75,) (72,)

**Comment by lucabaldini** [comment]
The phi distribution for the first energy bin is completely messed up. The other seem fine.

**Comment by lucabaldini** [comment]
Got it. We were using I (16-bit integers) to store the counts in the modulation cubes.

Switching to J (32-bit integers) solves the issue. This will give us (2**32 - 1)/2 or 2+ billion events per bin, which should be enough.
