### ISSUE TITLE
Python import conflict

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#96]
[lbaldini@nblbaldini evt]$ python fitting.py 
Traceback (most recent call last):
  File "fitting.py", line 22, in <module>
    from ximpol.evt.binning import xBinnedCountSpectrum
  File "/data/work/xipe/ximpol/ximpol/evt/binning.py", line 24, in <module>
    from astropy.io import fits
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/**init**.py", line 155, in <module>
    from .tests.runner import TestRunner
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/tests/runner.py", line 6, in <module>
    import multiprocessing
  File "/data/install/anaconda2/lib/python2.7/multiprocessing/**init**.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/data/install/anaconda2/lib/python2.7/multiprocessing/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
  File "/data/install/anaconda2/lib/python2.7/subprocess.py", line 427, in <module>
    import select
  File "/data/work/xipe/ximpol/ximpol/evt/select.py", line 23, in <module>
    from astropy.coordinates import SkyCoord
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/coordinates/__init__.py", line 13, in <module>
    from .baseframe import *
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/coordinates/baseframe.py", line 1181, in <module>
    from .earth import EarthLocation
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/coordinates/earth.py", line 11, in <module>
    from .builtin_frames import ITRS
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/**init**.py", line 28, in <module>
    from .fk5 import FK5
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py", line 12, in <module>
    from .utils import EQUINOX_J2000
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/utils.py", line 16, in <module>
    from ...utils import iers
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/utils/iers/**init**.py", line 4, in <module>
    from .iers import *
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 63, in <module>
    from ...table import Table, QTable
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/table/**init**.py", line 21, in <module>
    from .column import Column, MaskedColumn
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/table/column.py", line 19, in <module>
    from . import pprint
  File "/data/install/anaconda2/lib/python2.7/site-packages/astropy/table/pprint.py", line 15, in <module>
    from .. import log
ImportError: cannot import name log

**Comment by lucabaldini** [comment]
And the error is apparently a conflict between two select.py python modules.

This is not the first name clash that we observe, and we should pay attention to this systematically.

**Comment by lucabaldini** [comment]
evt.select.py moved to evt.subselect.py

(I am still not convinced that the use the astropy folks do of the "." in their imports makes sense.)
